In [1]:
akshit = '\u0905\u0915\u094D\u0937\u093F\u0924'
kotnala = '\u0915\u094B\u091F\u0928\u093E\u0932\u093E'
print(akshit, kotnala)

अक्षित कोटनाला

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('Market_Basket_Optimisation.csv', header=None)

In [4]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
trans=[]
for i in range(0,df.shape[0]):
    a=[str(item) for item in df.iloc[i] if str(item) !='nan']
    trans.append(a)
trans[:5]

[['shrimp',
  'almonds',
  'avocado',
  'vegetables mix',
  'green grapes',
  'whole weat flour',
  'yams',
  'cottage cheese',
  'energy drink',
  'tomato juice',
  'low fat yogurt',
  'green tea',
  'honey',
  'salad',
  'mineral water',
  'salmon',
  'antioxydant juice',
  'frozen smoothie',
  'spinach',
  'olive oil'],
 ['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea']]

In [6]:
te = TransactionEncoder()

te_ary = te.fit(trans).transform(trans)
df = pd.DataFrame(te_ary, columns=te.columns_)

feqi = apriori(df,min_support=0.03 , use_colnames=True)

rules = association_rules(feqi,metric="confidence",min_threshold=0.3)

# Filter the frequent itemsets to only those with 2 items (pairs)
pair_frequent_itemsets = feqi[feqi['itemsets'].apply(lambda x: len(x) == 2)]

# Print only the pairs
print(pair_frequent_itemsets)



rules

     support                            itemsets
36  0.033196                   (eggs, chocolate)
37  0.034395           (chocolate, french fries)
38  0.032129                   (milk, chocolate)
39  0.052660          (chocolate, mineral water)
40  0.039195              (chocolate, spaghetti)
41  0.036395                (eggs, french fries)
42  0.030796                        (eggs, milk)
43  0.050927               (eggs, mineral water)
44  0.036528                   (eggs, spaghetti)
45  0.033729       (french fries, mineral water)
46  0.035729  (frozen vegetables, mineral water)
47  0.031063          (green tea, mineral water)
48  0.040928        (ground beef, mineral water)
49  0.039195            (ground beef, spaghetti)
50  0.047994               (milk, mineral water)
51  0.035462                   (milk, spaghetti)
52  0.033729           (pancakes, mineral water)
53  0.059725          (spaghetti, mineral water)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(chocolate),(mineral water),0.163845,0.238368,0.052660,0.321400,1.348332,0.013604,1.122357,0.308965
1,(frozen vegetables),(mineral water),0.095321,0.238368,0.035729,0.374825,1.572463,0.013007,1.218270,0.402413
2,(ground beef),(mineral water),0.098254,0.238368,0.040928,0.416554,1.747522,0.017507,1.305401,0.474369
3,(ground beef),(spaghetti),0.098254,0.174110,0.039195,0.398915,2.291162,0.022088,1.373997,0.624943
4,(milk),(mineral water),0.129583,0.238368,0.047994,0.370370,1.553774,0.017105,1.209650,0.409465
5,(pancakes),(mineral water),0.095054,0.238368,0.033729,0.354839,1.488616,0.011071,1.180529,0.362712
6,(spaghetti),(mineral water),0.174110,0.238368,0.059725,0.343032,1.439085,0.018223,1.159314,0.369437

In [8]:
rules_h_c = association_rules(feqi,metric="confidence",min_threshold=0.5)

rules_h_c.head()

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction, zhangs_metric]
Index: []